### ISSUE TITLE
Allow multiple applications to be processed at once

### ISSUE THREAD

**Issue by lwl12** [veez21/terminal_app_systemizer#1]
My advice is waiting for the user command to exit. The current logic is very unreasonable for users like me who have 500+ applications, adding a serious amount of wating APP listing.

**Comment by lwl12** [comment]
Or simply allow users to enter the package name to specify the application

**Comment by veez21** [comment]
There's already a function to enter the package name.

**Comment by lwl12** [comment]
by label?But that seems still need to wait for the list

**Comment by veez21** [comment]
Yeah, it does. You can still use the apk function for the mean time. Doing it will be hard since some apps use almost the same label.

**Comment by lwl12** [comment]
OK Thanks
